[pytest]
pythonpath = .
testpaths = tests
asyncio_default_fixture_loop_scope = function
env =
	ENVIRONMENT=test
	MONGODB_URI=mongodb+srv://zimsec:PPGKfInJTGqA9pD7@cluster0.qlnn5na.mongodb.net
	MONGODB_DB=zimprep_test
	REDIS_URL=redis://localhost:6379/0
